---

name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/docker/metadata-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=sha
          type=semver,pattern={{version}}
        flavor: |
          latest=true

    - name: Push image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.meta.outputs.tags }}
        context: .
        push: true
